mel:
  n_mels: 128
  n_fft: 1024
  hop_length: 256
  f_min: 20
  f_max: 8000
  log_mel: true
  normalize: true

augment:
  time_mask: {enabled: true, max_mask_pct: 0.05, num_masks: 2}
  freq_mask: {enabled: true, max_mask_pct: 0.1, num_masks: 2}
  rir: {enabled: false}
  codec: {enabled: false}
  gain_noise: {enabled: true, snr_db: [10, 30]}
  mixup: {enabled: false, alpha: 0.2}
