defaults: []

dataset: tinysol  # tinysol | irmas | openmic
root_dir: data
sample_rate: 16000
num_workers: 4
subset:
  max_total_size_mb: 1000  # ≤ 1GB
  classes: []  # 선택 클래스 (빈 배열이면 기본값)
  max_files_per_class: 200
  max_duration_sec: null
