


seed: 42
batch_size: 16
epochs: 30
optimizer: adamw
lr: 3e-4
weight_decay: 1e-4
num_workers: 2
device: auto   # auto | cpu | cuda
val_ratio: 0.3
amp: true

kd:
  enabled: true
  alpha: 0.7
  temperature: 4.0

pruning:
  enabled: true
  global_unstructured_amount: 0.3
  structured_ln_amount: 0.2
  mode: progressive          # single | progressive
  progressive_steps: 3
  # When true and mode=progressive: interleave pruning with short fine-tunes
  interleaved_finetune: false
  # Epochs to fine-tune after each progressive pruning step (when interleaved)
  step_epochs: 2
  # Whether to prune.remove() after each step (recommended for interleaved)
  remove_after_each: true

logging:
  mlflow:
    enabled: true
    experiment_name: audio-kd-prune
    tracking_uri: file:./mlruns

# Checkpointing
checkpoint_dir: ./checkpoints
checkpoint_name: student_best.pt

# Early stopping (monitor val_macro_f1)
early_stopping:
  enabled: true
  patience: 5
  min_delta: 0.0005
