# Non-KD, Progressive Pruning


seed: 42
batch_size: 16
epochs: 30
optimizer: adamw
lr: 3e-4
weight_decay: 1e-4
num_workers: 2
device: auto
val_ratio: 0.3
amp: true
kd:
  enabled: false
pruning:
  enabled: true
  mode: progressive
  progressive_steps: 3
  global_unstructured_amount: 0.3
  structured_ln_amount: 0.2
logging:
  mlflow:
    enabled: true
    experiment_name: NonKD-Progressive
    tracking_uri: ./mlruns
checkpoint_dir: ./checkpoints
checkpoint_name: student_nonkd_none.pt
early_stopping:
  enabled: true
  patience: 5
  min_delta: 0.0005
